<?php return array (
  'sans-serif' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $fontDir . '/ZapfDingbats',
    'bold' => $fontDir . '/ZapfDingbats',
    'italic' => $fontDir . '/ZapfDingbats',
    'bold_italic' => $fontDir . '/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $fontDir . '/Symbol',
    'bold' => $fontDir . '/Symbol',
    'italic' => $fontDir . '/Symbol',
    'bold_italic' => $fontDir . '/Symbol',
  ),
  'serif' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $fontDir . '/DejaVuSans-Bold',
    'bold_italic' => $fontDir . '/DejaVuSans-BoldOblique',
    'italic' => $fontDir . '/DejaVuSans-Oblique',
    'normal' => $fontDir . '/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $fontDir . '/DejaVuSansMono-Bold',
    'bold_italic' => $fontDir . '/DejaVuSansMono-BoldOblique',
    'italic' => $fontDir . '/DejaVuSansMono-Oblique',
    'normal' => $fontDir . '/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $fontDir . '/DejaVuSerif-Bold',
    'bold_italic' => $fontDir . '/DejaVuSerif-BoldItalic',
    'italic' => $fontDir . '/DejaVuSerif-Italic',
    'normal' => $fontDir . '/DejaVuSerif',
  ),
  'glyphicons halflings' => array(
    'normal' => $fontDir . '/glyphicons-halflings-normal_02b2bc544e3f2ca48f07e0b5a0f34a68',
  ),
  'fontawesome' => array(
    'normal' => $fontDir . '/fontawesome-normal_6d41769823fd665174afafce7588b3e6',
  ),
  'roboto' => array(
    '300' => $fontDir . '/roboto-300_bbbaaf854d41f449c323a134d6cdb640',
    'normal' => $fontDir . '/roboto-normal_ff96aae427783c4ad5bcbdd9f124e897',
    '500' => $fontDir . '/roboto-500_3d72e87725183d880798bb63c4fcb888',
    'bold' => $fontDir . '/roboto-bold_763902166f5009bab217919035564722',
  ),
  'open sans' => array(
    'italic' => $fontDir . '/open-sans-italic_27fb03d2bf8c49880fbd15f3f96b7504',
    '600_italic' => $fontDir . '/open-sans-600-italic_d1b486ea88688c1629a580f4d3892e32',
    'bold_italic' => $fontDir . '/open-sans-bold-italic_68f518df61d7a8314654ce172af86e08',
    '300' => $fontDir . '/open-sans-300_771fb82d4990c29fe5ca012c48dba770',
    'normal' => $fontDir . '/open-sans-normal_a5a5970acc26f679ed9ad7632d8572df',
    '600' => $fontDir . '/open-sans-600_132792df4309018ac172d56fb73c5a4c',
    'bold' => $fontDir . '/open-sans-bold_e153176450f92f468fa14d9de918408b',
    '800' => $fontDir . '/open-sans-800_9b31cb72fa555985c61d89917ed8cb08',
  ),
  'montserrat' => array(
    'normal' => $fontDir . '/montserrat-normal_99765fdb334a0a22a804b94acf422542',
    'bold' => $fontDir . '/montserrat-bold_25db19d51f848aaee2651f1059e63d4f',
  ),
) ?>